# Options here can still be overridden by cmd line args.
#   sidekiq -C sidekiq.yml
---
:verbose: false
:pidfile: ./tmp/pids/sidekiq.pid  
:logfile: ./log/sidekiq.log
:timeout: 300
development:
  :concurrency: 6
production:
  :concurrency: 50
:queues:
  - [a, 5]
  - [b, 3]
  - [c, 2]
  - [default, 3]
